# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  gateway:
    container_name: hermes
    image: nousresearch/hermes-agent:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/hermes/gateway/data:/opt/data
      - ./config/config.yaml:/opt/data/config.yaml
      - /mnt/cache/appdata/hermes/shared/certs:/certs
    networks:
      - net
      - searxng
    environment:
      TZ: "America/Chicago"
      OPENCODE_GO_API_KEY: "${OPENCODE_GO_API_KEY}"
      SEARXNG_URL: "http://searxng:8888"
      FIRECRAWL_API_KEY: "${FIRECRAWL_API_KEY}"
      TAVILY_API_KEY: "${TAVILY_API_KEY}"
      EXA_API_KEY: "${EXA_API_KEY}"
      MATRIX_HOMESERVER: "https://matrix.trkm.io"
      MATRIX_ACCESS_TOKEN: "${MATRIX_ACCESS_TOKEN}"
      MATRIX_RECOVERY_KEY: "${MATRIX_RECOVERY_KEY}"
      MATRIX_ALLOWED_USERS: "${MATRIX_ALLOWED_USERS}"
      MATRIX_ENCRYPTION: "true"
      GITHUB_PERSONAL_ACCESS_TOKEN: "${GITHUB_PERSONAL_ACCESS_TOKEN}"
      DOCKER_HOST: "tcp://dind:2376"
      DOCKER_CERT_PATH: "/certs"
    command: gateway run

  dind:
    container_name: hermes_dind
    image: docker:dind
    restart: unless-stopped
    privileged: true
    volumes:
      - /mnt/cache/appdata/hermes/shared/certs:/certs
    networks:
      - net
    environment:
      TZ: "America/Chicago"
      DOCKER_TLS_CERTDIR: "/certs"

networks:
  net:
  searxng:
    external: true