services:
  suite:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/npm/@lobehub/icons-static-png@latest/dark/hermesagent.png"
      net.unraid.docker.webui: "https://hermes.trkm.io"
      net.unraid.docker.shell: "/bin/bash"
