# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  gateway:
    container_name: hermes
    image: nousresearch/hermes-agent:latest
    restart: unless-stopped
    command: gateway run
    volumes:
      - /mnt/cache/appdata/hermes/gateway/data:/opt/data
    networks:
      - net
    environment:
      TZ: "America/Chicago"
      OPENCODE_GO_API_KEY: "${OPENCODE_GO_API_KEY}"
      MATRIX_HOMESERVER: "https://matrix.trkm.io"
      MATRIX_ACCESS_TOKEN: "${MATRIX_ACCESS_TOKEN}"
      MATRIX_ENCRYPTION: "true"
      MATRIX_DEVICE_ID: "hermes-gateway"
      MATRIX_ALLOWED_USERS: "@trkm:matrix.trkm.io"
      MATRIX_HOME_ROOM: "!UWpsgEh7fDahQ9ykFt:matrix.trkm.io"
      MATRIX_RECOVERY_KEY: "${MATRIX_RECOVERY_KEY}"

networks:
  net:
