# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  hd:
    container_name: radarr_hd
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/radarr/hd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr_hd.rule: "Host(`radarr.trkm.io`)"
      traefik.http.services.radarr_hd.loadBalancer.server.port: "7878"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr.png"
      net.unraid.docker.webui: "https://radarr.trkm.io"
      net.unraid.docker.shell: "/bin/bash"

  uhd:
    container_name: radarr_uhd
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/radarr/uhd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr_uhd.rule: "Host(`radarr.trkm.io`) && PathPrefix(`/uhd`)"
      traefik.http.services.radarr_uhd.loadBalancer.server.port: "7878"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr.png"
      net.unraid.docker.webui: "https://radarr.trkm.io/uhd"
      net.unraid.docker.shell: "/bin/bash"

  anime:
    container_name: radarr_anime
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/radarr/anime/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.radarr_anime.rule: "Host(`radarr.trkm.io`) && PathPrefix(`/anime`)"
      traefik.http.services.radarr_anime.loadBalancer.server.port: "7878"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/radarr.png"
      net.unraid.docker.webui: "https://radarr.trkm.io/anime"
      net.unraid.docker.shell: "/bin/bash"

networks:
  pvr:
    external: true
  proxy:
    external: true
