# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  litellm:
    container_name: litellm
    image: ghcr.io/berriai/litellm:main-latest
    restart: unless-stopped
    ports:
      - 4000:4000
    volumes:
      - /mnt/user/appdata/litellm/config.yaml:/app/config.yaml:ro
    networks:
      - postgres
      - llm
      - proxy
    environment:
      TZ: America/Chicago
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      LITELLM_SALT_KEY: ${LITELLM_SALT_KEY}
      DATABASE_URL: ${DATABASE_URL}
      STORE_MODEL_IN_DB: "True"
    command: ["--config", "/app/config.yaml"]
    labels:
      traefik.enable: true
      traefik.http.routers.litellm.rule: Host(`litellm.trkm.io`)
      traefik.http.services.litellm.loadBalancer.server.port: 4000
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/litellm.png
      net.unraid.docker.webui: https://litellm.trkm.io
      net.unraid.docker.shell: /bin/sh

networks:
  postgres:
    external: true
  llm:
    external: true
  proxy:
    external: true
