# generated by datamodel-codegen:
#   filename:  models_dev_provider_composite.json
#   timestamp: 2026-07-10T16:04:55+00:00
#
# Refactored to use dict[str, Model] for the models field and root ModelCatalog type.

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, RootModel


# ── Enums ──────────────────────────────────────────────────────────────────────


class ModalityType(StrEnum):
    text = "text"
    image = "image"
    audio = "audio"
    video = "video"
    pdf = "pdf"


class ReasoningOptionType(StrEnum):
    effort = "effort"
    budget_tokens = "budget_tokens"
    toggle = "toggle"


class CostTierType(StrEnum):
    context = "context"


# ── Input schemas (models.dev) ─────────────────────────────────────────────────


class ReasoningOption(BaseModel):
    type: ReasoningOptionType | None = None
    values: list[str | None] | None = None


class Modalities(BaseModel):
    input: list[ModalityType] | None = None
    output: list[ModalityType] | None = None


class Limit(BaseModel):
    context: int | None = None
    output: int | None = None


class TierTier(BaseModel):
    type: CostTierType | None = None
    size: int | None = None


class Tier(BaseModel):
    input: float | None = None
    output: float | None = None
    cache_read: float | None = None
    tier: TierTier | None = None


class ContextOver200k(BaseModel):
    input: float | None = None
    output: float | None = None
    cache_read: float | None = None
    cache_write: float | None = None


class Cost(BaseModel):
    input: float | None = None
    output: float | None = None
    cache_read: float | None = None
    cache_write: float | None = None
    tiers: list[Tier] | None = None
    context_over_200k: ContextOver200k | None = None


class Model(BaseModel):
    id: str | None = None
    name: str | None = None
    description: str | None = None
    family: str | None = None
    attachment: bool | None = None
    reasoning: bool | None = None
    reasoning_options: list[ReasoningOption] | None = None
    tool_call: bool | None = None
    structured_output: bool | None = None
    temperature: bool | None = None
    knowledge: str | None = None
    release_date: str | None = None
    last_updated: str | None = None
    modalities: Modalities | None = None
    open_weights: bool | None = None
    limit: Limit | None = None
    cost: Cost | None = None


class Provider(BaseModel):
    id: str | None = None
    name: str | None = None
    env: list[str] | None = None
    npm: str | None = None
    api: str | None = None
    doc: str | None = None
    models: dict[str, Model] | None = None


class ModelCatalog(RootModel[dict[str, Provider]]):
    """Top-level models.dev catalog, a dict of provider_id → Provider."""
    pass
