services:
  bridge:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/proton-mail-bridge.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"
