# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  server:
    container_name: authentik
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION}
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/authentik/shared/data:/data
      - /mnt/cache/appdata/authentik/shared/templates:/templates
    networks:
      - net
      - proxy
      - postgres
    environment:
      TZ: "America/Chicago"
      AUTHENTIK_POSTGRESQL__HOST: "postgres"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${POSTGRES_PASSWORD}"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
    command: ["server"]
    labels:
      traefik.enable: "true"
      traefik.http.routers.authentik.rule: "Host(`auth.trkm.io`)"
      traefik.http.services.authentik.loadBalancer.server.port: "9000"

  worker:
    container_name: authentik_worker
    image: ghcr.io/goauthentik/server:${AUTHENTIK_VERSION}
    restart: unless-stopped
    user: "root"
    volumes:
      - /mnt/cache/appdata/authentik/shared/data:/data
      - /mnt/cache/appdata/authentik/shared/templates:/templates
      - /mnt/cache/appdata/authentik/worker/certs:/certs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
      - postgres
    environment:
      TZ: "America/Chicago"
      AUTHENTIK_POSTGRESQL__HOST: "postgres"
      AUTHENTIK_POSTGRESQL__NAME: "authentik"
      AUTHENTIK_POSTGRESQL__USER: "authentik"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${POSTGRES_PASSWORD}"
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"
    command: ["worker"]

networks:
  net:
  proxy:
    external: true
  postgres:
    external: true
