# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    depends_on:
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2376
      DOCKER_TLS_VERIFY: 1
      DOCKER_CERT_PATH: /certs/client
    volumes:
      - /mnt/user/appdata/gitlab-runner/config:/etc/gitlab-runner
      - /mnt/user/appdata/gitlab-runner/builds:/builds
      - /mnt/user/appdata/gitlab-runner/cache:/cache
      - /mnt/user/appdata/gitlab-runner/dind/certs:/certs:ro
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/gitlab.png
      net.unraid.docker.shell: /bin/bash

  dind:
    container_name: gitlab-runner-dind
    image: docker:dind
    hostname: dind
    restart: unless-stopped
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - /mnt/user/appdata/gitlab-runner/dind/certs:/certs
      - /mnt/cache/appdata/gitlab-runner/dind/data:/var/lib/docker
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/docker.png
      net.unraid.docker.shell: /bin/sh
    command: ["--tls=true"]
