services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/home-assistant.png"
      net.unraid.docker.webui: "https://ha.trkm.io"
      net.unraid.docker.shell: "/bin/bash"
