# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: homeassistant
    image: lscr.io/linuxserver/homeassistant:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/homeassistant/app/config:/config
    networks:
      br0:
        ipv4_address: 10.10.20.3
      proxy:
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.homeassistant.rule: "Host(`ha.trkm.io`)"
      traefik.http.services.homeassistant.loadBalancer.server.port: "8123"

networks:
  br0:
    external: true
  proxy:
    external: true
