# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  mcp-portainer:
    container_name: mcp_portainer
    image: registry.gitlab.com/trkm/mcp-container:latest
    restart: unless-stopped
    networks:
      - mcp
    environment:
      TZ: America/Chicago
      MCP_TRANSPORT: sse
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8000
      MCP_TOKEN: ${MCP_TOKEN}
      CONTAINER_PROVIDER__DEFAULT__TYPE: portainer
      CONTAINER_PROVIDER__DEFAULT__URL: http://portainer:9000
      CONTAINER_PROVIDER__DEFAULT__TOKEN: ${PORTAINER_API_KEY}
      CONTAINER_PROVIDER__DEFAULT__GIT_USERNAME: ${GITLAB_API_USER}
      CONTAINER_PROVIDER__DEFAULT__GIT_TOKEN_REPO_READ: ${GITLAB_TOKEN_REPO_READ}
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/portainer.png
      net.unraid.docker.shell: /bin/bash

  mcp-gitlab:
    container_name: mcp_gitlab
    image: registry.gitlab.com/trkm/mcp-git:latest
    restart: unless-stopped
    networks:
      - mcp
    environment:
      TZ: America/Chicago
      MCP_TRANSPORT: sse
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8000
      MCP_TOKEN: ${MCP_TOKEN}
      GIT_PROVIDER__DEFAULT__TYPE: gitlab
      GIT_PROVIDER__DEFAULT__URL: https://gitlab.com
      GIT_PROVIDER__DEFAULT__TOKEN: ${GITLAB_API_TOKEN}
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/gitlab.png
      net.unraid.docker.shell: /bin/bash

networks:
  mcp:
    external: true
