# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  server:
    container_name: immich
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /mnt/user/data/photos:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - net
      - proxy
      - postgres
    environment:
      TZ: "America/Chicago"
      DB_HOSTNAME: "postgres"
      DB_USERNAME: "immich"
      DB_PASSWORD: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
      DB_VECTOR_EXTENSION: "vectorchord"
      REDIS_HOSTNAME: "cache"
      IMMICH_MACHINE_LEARNING_URL: "http://ml:3003"
    depends_on:
      - cache
    healthcheck:
      disable: false
    labels:
      traefik.enable: "true"
      traefik.http.routers.immich.rule: "Host(`immich.trkm.io`)"
      traefik.http.services.immich.loadBalancer.server.port: "2283"

  ml:
    container_name: immich_ml
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION}
    restart: unless-stopped
    volumes:
      - model_cache:/cache
    networks:
      - net
    environment:
      TZ: "America/Chicago"
    healthcheck:
      disable: false

  cache:
    container_name: immich_cache
    image: docker.io/valkey/valkey:9
    restart: unless-stopped
    networks:
      - net
    environment:
      TZ: "America/Chicago"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]

volumes:
  model_cache:

networks:
  net:
  proxy:
    external: true
  postgres:
    external: true
