# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  gateway:
    container_name: tensorzero
    image: ghcr.io/trent-maetzold/tensorzero-gateway:oauth-test
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/tensorzero/config:/app/config:ro
    networks:
      - clickhouse
      - postgres
      - proxy
    environment:
      TZ: America/Chicago
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      TENSORZERO_CLICKHOUSE_URL: http://clickhouse:${CLICKHOUSE_PASSWORD}@clickhouse:8123/tensorzero
      TENSORZERO_POSTGRES_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/tensorzero
    depends_on:
      health:
        condition: service_healthy
    command: ["--config-file", "config/tensorzero.toml"]
    labels:
      traefik.enable: true
      traefik.http.routers.tensorzero.rule: Host(`llm.trkm.io`)
      traefik.http.services.tensorzero.loadBalancer.server.port: 3000
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/148420822
      net.unraid.docker.webui: https://llm.trkm.io
      net.unraid.docker.shell: /bin/sh

  ui:
    container_name: tensorzero_ui
    image: tensorzero/ui
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/tensorzero/config:/app/config:ro
    networks:
      - clickhouse
      - postgres
      - proxy
    environment:
      TZ: America/Chicago
      TENSORZERO_GATEWAY_URL: http://gateway:3000
      TENSORZERO_CLICKHOUSE_URL: http://clickhouse:${CLICKHOUSE_PASSWORD}@clickhouse:8123/tensorzero
    depends_on:
      health:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.http.routers.tensorzero-ui.rule: Host(`t0.trkm.io`)
      traefik.http.services.tensorzero-ui.loadBalancer.server.port: 4000
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/148420822
      net.unraid.docker.webui: https://t0.trkm.io
      net.unraid.docker.shell: /bin/sh

  health:
    container_name: tensorzero_health
    image: busybox
    restart: unless-stopped
    networks:
      - clickhouse
      - postgres
    environment:
      TZ: America/Chicago
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --spider --tries 1 http://clickhouse:${CLICKHOUSE_PASSWORD}@clickhouse:8123/ping && nc -z postgres 5432",
        ]
      interval: 5s
      retries: 12
      start_period: 30s
      start_interval: 1s
      timeout: 2s
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    labels:
      net.unraid.docker.icon: https://avatars.githubusercontent.com/u/148420822
      net.unraid.docker.shell: /bin/sh

networks:
  clickhouse:
    external: true
  postgres:
    external: true
  proxy:
    external: true
