services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/headscale.png"
      net.unraid.docker.webui: "https://hs.trkm.io/admin"
      net.unraid.docker.shell: ""

  ui:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/tale/headplane/refs/heads/main/public/favicon.ico"
      net.unraid.docker.webui: "https://hs.trkm.io/admin"
      net.unraid.docker.shell: ""
