# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: tuwunel
    image: jevolk/tuwunel:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/tuwunel/app/config:/var/lib/tuwunel
    networks:
      - proxy
    environment:
      TZ: "America/Chicago"
      TUWUNEL_SERVER_NAME: "matrix.trkm.io"
      TUWUNEL_DATABASE_PATH: "/var/lib/tuwunel"
      TUWUNEL_PORT: "6167"
      TUWUNEL_ADDRESS: "0.0.0.0"
      TUWUNEL_MAX_REQUEST_SIZE: "20000000"
      TUWUNEL_ALLOW_REGISTRATION: "true"
      TUWUNEL_REGISTRATION_TOKEN: "${TUWUNEL_REGISTRATION_TOKEN:?TUWUNEL_REGISTRATION_TOKEN is required}"
      TUWUNEL_ALLOW_FEDERATION: "true"
      TUWUNEL_TRUSTED_SERVERS: '["matrix.org"]'
      TUWUNEL_WELL_KNOWN: |
        {
        client=https://matrix.trkm.io,
        server=matrix.trkm.io:443
        }
    ulimits:
      nofile:
        soft: 1048567
        hard: 1048567
    labels:
      traefik.enable: "true"
      traefik.http.routers.tuwunel.rule: "Host(`matrix.trkm.io`)"
      traefik.http.services.tuwunel.loadBalancer.server.port: "6167"

networks:
  proxy:
    external: true
