services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/matrix.png"
      net.unraid.docker.webui: "https://matrix.trkm.io"
      net.unraid.docker.shell: "/bin/sh"
