services:
  server:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/woodpecker-ci.png"
      net.unraid.docker.webui: "https://ci.trkm.io"
      net.unraid.docker.shell: "/bin/sh"

  agent:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/woodpecker-ci.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/sh"

  dind:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/docker.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/sh"

  buildkit:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/docker.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: ""

  db:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/postgres.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"
