# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/lidarr/app/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
      - postgres
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
      LIDARR__APP__INSTANCENAME: "Lidarr"
      LIDARR__APP__URLBASE: ""
      LIDARR__AUTH__METHOD: "External"
      LIDARR__AUTH__APIKEY: "${ARR_API_KEY}"
      LIDARR__UPDATE__MECHANISM: "Docker"
      LIDARR__POSTGRES__HOST: "postgres"
      LIDARR__POSTGRES__USER: "lidarr"
      LIDARR__POSTGRES__PASSWORD: "${POSTGRES_PASSWORD}"
      LIDARR__POSTGRES__MAINDB: "lidarr"
      LIDARR__POSTGRES__LOGDB: "lidarr_log"
    labels:
      traefik.enable: "true"
      traefik.http.routers.lidarr.rule: "Host(`lidarr.trkm.io`)"
      traefik.http.services.lidarr.loadBalancer.server.port: "8686"

networks:
  pvr:
    external: true
  proxy:
    external: true
  postgres:
    external: true
