services:
  runner_user:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"

  runner_org:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/github.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"

  dind:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/docker.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/sh"
