# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/prowlarr/app/config:/config
    networks:
      - pvr
      - proxy
      - postgres
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
      PROWLARR__APP__INSTANCENAME: "Prowlarr"
      PROWLARR__APP__URLBASE: ""
      PROWLARR__AUTH__METHOD: "External"
      PROWLARR__AUTH__APIKEY: "${ARR_API_KEY}"
      PROWLARR__UPDATE__MECHANISM: "Docker"
      PROWLARR__POSTGRES__HOST: "postgres"
      PROWLARR__POSTGRES__USER: "prowlarr"
      PROWLARR__POSTGRES__PASSWORD: "${POSTGRES_PASSWORD}"
      PROWLARR__POSTGRES__MAINDB: "prowlarr"
      PROWLARR__POSTGRES__LOGDB: "prowlarr_log"
    labels:
      traefik.enable: "true"
      traefik.http.routers.prowlarr.rule: "Host(`prowlarr.trkm.io`)"
      traefik.http.services.prowlarr.loadBalancer.server.port: "9696"

networks:
  pvr:
    external: true
  proxy:
    external: true
  postgres:
    external: true
