session:
  cookies:
    - domain: "trkm.io"
      authelia_url: "https://auth.trkm.io"
      default_redirection_url: "https://auth.trkm.io/settings"

access_control:
  default_policy: two_factor
  rules:
    - domain:
        - "auth.trkm.io"
        - "ha.trkm.io"
        - "hs.trkm.io"
        - "matrix.trkm.io"
        - "seerr.trkm.io"
        - "tea.trkm.io"
      policy: bypass

    - domain:
        - "bt.trkm.io"
        - "chat.trkm.io"
        - "immich.trkm.io"
        - "lidarr.trkm.io"
        - "nzb.trkm.io"
        - "prowlarr.trkm.io"
      resources:
        - "^/api/"
      policy: bypass

    - domain:
        - "radarr.trkm.io"
        - "sonarr.trkm.io"
      resources:
        - "^/hd/api/"
        - "^/uhd/api/"
        - "^/anime/api/"
      policy: bypass

    - domain: "api.trkm.io"
      resources:
        - "^/t0/"
        - "^/mcp"
        - "^/webhook/github"
      policy: bypass

    - domain: "dav.trkm.io"
      resources:
        - "^/.well-known/"
        - "^/dav.php/"
      policy: bypass
