services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/IBM/mcp-context-forge/main/docs/docs/images/contextforge-logo_horizontal_black.png"
      net.unraid.docker.webui: "https://api.trkm.io/mcp/admin"
      net.unraid.docker.shell: "/bin/sh"
