# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  contextforge:
    container_name: contextforge
    image: ghcr.io/ibm/mcp-context-forge:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/contextforge/data:/data
    networks:
      - mcp
      - proxy
    environment:
      TZ: "America/Chicago"
      DATABASE_URL: "sqlite+aiosqlite:////data/contextforge.db"
      LOG_LEVEL: "INFO"
      TRANSPORT_TYPE: "all"
      AUTH_REQUIRED: "False"
    labels:
      traefik.enable: "true"
      traefik.http.routers.contextforge.rule: "Host(`api.trkm.io`)"
      traefik.http.services.contextforge.loadBalancer.server.port: "4444"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/IBM/mcp-context-forge/main/docs/docs/images/contextforge-logo_horizontal_black.png"
      net.unraid.docker.shell: "/bin/sh"

networks:
  mcp:
    external: true
  proxy:
    external: true
