# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  hd:
    container_name: sonarr_hd
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sonarr/hd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr_hd.rule: "Host(`sonarr.trkm.io`)"
      traefik.http.services.sonarr_hd.loadBalancer.server.port: "8989"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sonarr.png"
      net.unraid.docker.webui: "https://sonarr.trkm.io"
      net.unraid.docker.shell: "/bin/bash"

  uhd:
    container_name: sonarr_uhd
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sonarr/uhd/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr_uhd.rule: "Host(`sonarr.trkm.io`) && PathPrefix(`/uhd`)"
      traefik.http.services.sonarr_uhd.loadBalancer.server.port: "8989"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sonarr.png"
      net.unraid.docker.webui: "https://sonarr.trkm.io/uhd"
      net.unraid.docker.shell: "/bin/bash"

  anime:
    container_name: sonarr_anime
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sonarr/anime/config:/config
      - /mnt/user/data:/data
    networks:
      - pvr
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.sonarr_anime.rule: "Host(`sonarr.trkm.io`) && PathPrefix(`/anime`)"
      traefik.http.services.sonarr_anime.loadBalancer.server.port: "8989"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sonarr.png"
      net.unraid.docker.webui: "https://sonarr.trkm.io/anime"
      net.unraid.docker.shell: "/bin/bash"

networks:
  pvr:
    external: true
  proxy:
    external: true
