# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    restart: unless-stopped
    volumes:
      - /mnt/user/appdata/sabnzbd/config:/config
      - /mnt/user/data/usenet:/data/usenet
    network_mode: container:gluetun
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: America/Chicago
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.rule: Host(`sabnzbd.trkm.io`)
      traefik.http.services.sabnzbd.loadBalancer.server.port: 8080
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/sabnzbd.png
      net.unraid.docker.webui: https://sabnzbd.trkm.io
      net.unraid.docker.shell: /bin/bash
