services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/sabnzbd.png"
      net.unraid.docker.webui: "https://nzb.trkm.io"
      net.unraid.docker.shell: "/bin/bash"

  vpn:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/gluetun.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/sh"
