services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/plex.png"
      net.unraid.docker.webui: "https://app.plex.tv"
      net.unraid.docker.shell: "/bin/bash"
