services:
  db:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/clickhouse.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"
