services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/gitea.png"
      net.unraid.docker.webui: "https://tea.trkm.io"
      net.unraid.docker.shell: "/bin/bash"

  postgres:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/postgres.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: ""