services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/png/gitea.png"
      net.unraid.docker.webui: "https://tea.trkm.io"
      net.unraid.docker.shell: "/bin/bash"

  db:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/postgres.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"

