# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
services:
  tailscale:
    container_name: traefik-tailscale
    image: tailscale/tailscale:latest
    hostname: traefik-dmz
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /mnt/user/appdata/traefik/ts:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    environment:
      TS_STATE_DIR: /var/lib/tailscale
      TS_SOCKET: /var/lib/tailscale/tailscaled.sock
      TS_USERSPACE: false
      TS_LOGIN_SERVER: https://hs.trkm.io
    networks:
      dmz:
        ipv4_address: 10.10.30.10
      proxy: null
  traefik:
    container_name: traefik
    image: traefik:v3.6
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/user/appdata/traefik/dynamic:/etc/traefik/dynamic
      - /mnt/user/appdata/traefik/letsencrypt:/letsencrypt
      - /mnt/user/appdata/traefik/log:/var/log
      - /mnt/user/appdata/traefik/ts:/var/lib/tailscale:ro
    environment:
      CF_API_EMAIL: tkm89@proton.me
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
      CF_ZONE_API_TOKEN: ${CF_ZONE_API_TOKEN}
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --log.level=INFO
      - --log.filepath=/var/log/traefik.log
      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik-access.log
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy
      - --providers.docker.watch=true
      - --entryPoints.web.address=:80
      - --entryPoints.web.http.redirections.entryPoint.to=websecure
      - --entryPoints.web.http.redirections.entryPoint.scheme=https
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.asDefault=true
      - --entryPoints.websecure.http.tls.certResolver=cloudflare
      - --certificatesResolvers.cloudflare.acme.email=tkm89@proton.me
      - --certificatesResolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.cloudflare.acme.dnsChallenge=true
      - --certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare
      - --serversTransport.insecureSkipVerify=true
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.trkm.io`)
      traefik.http.services.traefik.loadBalancer.server.port: 8080
      net.unraid.docker.icon: https://raw.githubusercontent.com/ibracorp/unraid-templates/master/traefik/traefik.png
      net.unraid.docker.webui: https://traefik.trkm.io
      net.unraid.docker.shell: /bin/bash
  traefik-tunnel:
    container_name: traefik-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    networks:
      - proxy
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN}
    command: tunnel run
networks:
  dmz:
    driver: ipvlan
    driver_opts:
      parent: br0.30
    ipam:
      config:
        - subnet: 10.10.30.0/24
          gateway: 10.10.30.1
  proxy:
    external: true
