# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  proxy:
    container_name: traefik
    hostname: proxy
    image: traefik:v3
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/dynamic:/etc/traefik/dynamic
      - /mnt/cache/appdata/traefik/proxy/letsencrypt:/letsencrypt
      - /mnt/cache/appdata/traefik/proxy/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      br0:
        ipv4_address: 10.10.20.10
      proxy:
    environment:
      TZ: "America/Chicago"
      CF_API_EMAIL: "tkm89@proton.me"
      CF_DNS_API_TOKEN: "${CF_DNS_API_TOKEN}"
      CF_ZONE_API_TOKEN: "${CF_ZONE_API_TOKEN}"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--log.level=INFO"
      - "--log.filepath=/var/log/traefik.log"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik-access.log"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.network=proxy"
      - "--providers.docker.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.web.http.redirections.entryPoint.to=websecure"
      - "--entryPoints.web.http.redirections.entryPoint.scheme=https"
      - "--entryPoints.web.http.redirections.entryPoint.permanent=true"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.websecure.asDefault=true"
      - "--entryPoints.websecure.http.tls.certResolver=cloudflare"
      - "--certificatesResolvers.cloudflare.acme.email=tkm89@proton.me"
      - "--certificatesResolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
      - "--certificatesResolvers.cloudflare.acme.dnsChallenge=true"
      - "--certificatesResolvers.cloudflare.acme.dnsChallenge.provider=cloudflare"
      - "--serversTransport.insecureSkipVerify=true"
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.trkm.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      traefik.http.routers.traefik.service: "api@internal"
      traefik.http.services.traefik.loadBalancer.server.port: "80"

  vpn:
    container_name: traefik_ts
    image: ghcr.io/tailscale/tailscale:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /mnt/cache/appdata/traefik/vpn/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    network_mode: service:proxy
    environment:
      TZ: "America/Chicago"
      TS_AUTH_ONCE: "true"
      TS_AUTHKEY: "${TS_AUTHKEY}"
      TS_USERSPACE: "false"
      TS_ACCEPT_DNS: "true"
      TS_STATE_DIR: "/var/lib/tailscale"
      TS_EXTRA_ARGS: "--login-server=https://hs.trkm.io"
    depends_on:
      - proxy

networks:
  br0:
    external: true
  proxy:
    external: true
