# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/baikal/app/config:/var/www/baikal/config
    networks:
      - proxy
      - postgres
    environment:
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.baikal.rule: "Host(`dav.trkm.io`)"
      traefik.http.services.baikal.loadBalancer.server.port: "80"

networks:
  proxy:
    external: true
  postgres:
    external: true
