services:
  app:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://hotio.dev/webhook-avatars/cloudflareddns.png"
      net.unraid.docker.webui: ""
      net.unraid.docker.shell: "/bin/bash"
