# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: seerr
    image: ghcr.io/seerr-team/seerr:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/seerr/app/config:/app/config
    networks:
      - proxy
      - postgres
    environment:
      TZ: "America/Chicago"
      DB_TYPE: "postgres"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_NAME: "seerr"
      DB_USER: "seerr"
      DB_PASS: "${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}"
    labels:
      traefik.enable: "true"
      traefik.http.routers.seerr.rule: "Host(`seerr.trkm.io`)"
      traefik.http.services.seerr.loadBalancer.server.port: "5055"

networks:
  proxy:
    external: true
  postgres:
    external: true
