# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  overseerr:
    container_name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    ports:
      - 5055:5055
    volumes:
      - /mnt/user/appdata/overseerr/config:/config
    networks:
      - proxy
    environment:
      PUID: "99"
      PGID: "100"
      UMASK: "022"
      TZ: America/Chicago
    labels:
      traefik.enable: true
      traefik.http.routers.overseerr.rule: Host(`overseerr.trkm.io`)
      traefik.http.services.overseerr.loadBalancer.server.port: 5055
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/overseerr.png
      net.unraid.docker.webui: https://overseerr.trkm.io
      net.unraid.docker.shell: /bin/bash

networks:
  proxy:
    external: true
