# =============================================================================
# Coding
# =============================================================================

[functions.coding_fast]
type = "chat"

[functions.coding_fast.variants.coding_fast]
type = "chat_completion"
model = "claude_sonnet_4_6"
reasoning_effort = "low"

[functions.coding_careful]
type = "chat"

[functions.coding_careful.variants.coding_careful]
type = "chat_completion"
model = "claude_opus_4_6"
reasoning_effort = "high"
