services:
  zot:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://avatars.githubusercontent.com/u/93798821?v=4"
      net.unraid.docker.webui: "https://reg.trkm.io"
      net.unraid.docker.shell: ""
