# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  registry:
    container_name: zot
    image: ghcr.io/project-zot/zot:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/zot/registry/registry:/var/lib/registry
    networks:
      - proxy
    environment:
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.zot.rule: "Host(`reg.trkm.io`)"
      traefik.http.services.zot.loadBalancer.server.port: "5000"

networks:
  proxy:
    external: true
