services:
  zot:
    labels:
      net.unraid.docker.managed: "composeman"
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/selfhst/icons/svg/zot-registry-light.svg"
      net.unraid.docker.webui: "https://reg.trkm.io"
      net.unraid.docker.shell: ""
