# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /mnt/user/appdata/qbittorrent/vpn:/gluetun
    networks:
      - pvr
    environment:
      TZ: America/Chicago
      VPN_SERVICE_PROVIDER: protonvpn
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_CITIES: Chicago
    labels:
      net.unraid.docker.icon: https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/png/gluetun.png
      net.unraid.docker.shell: /bin/sh

networks:
  pvr:
    external: true
