# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json

services:
  app:
    container_name: example
    image: example/image:latest
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/example/app/config:/config
    networks:
      - proxy
    environment:
      TZ: "America/Chicago"
    labels:
      traefik.enable: "true"
      traefik.http.routers.example.rule: "Host(`example.trkm.io`)"
      traefik.http.services.example.loadBalancer.server.port: "8080"

networks:
  proxy:
    external: true
